---
#- name: echo some variables
#  ansible.builtin.debug:
#    msg: 
#      - rhel9_use_tailoring_file = {{ rhel9_use_tailoring_file }}
#      - rhel8_use_tailoring_file = {{ rhel8_use_tailoring_file }}
#      - rhel7_use_tailoring_file = {{ rhel7_use_tailoring_file }}

- name: include variables for os version
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"

- name: install scap content
  ansible.builtin.yum:
    name: scap-security-guide
    state: latest

- name: copy tailoring file if required
  ansible.builtin.copy:
    src: "{{ scap_tfile_source }}"
    dest: "{{ scap_tfile_dest }}"
    owner: root
    group: root
    mode: '0644'
  when: 
    - scap_use_tailoring_file == "true"
    - scap_tile_source is defined

- name: run scan without tailoring
  ansible.builtin.shell: oscap xccdf eval --profile {{ scap_profile_name }} --results {{ results_file }} --report {{ report_file }} {{ scap_source_file }} 2>/dev/null
  ignore_errors: True
  when: 
    - scap_use_tailoring_file == "false"

- name: run the scan with tailoring
  ansible.builtin.shell: oscap xccdf eval --profile {{ scap_tailored_profile }} --tailoring-file {{ scap_tfile_dest }} --results {{ results_file }} --report {{ report_file }} {{ scap_source_file }} 2>/dev/null
  ignore_errors: True
  when: 
    - scap_use_tailoring_file == "true"

- name: copy scan report to report server
  ansible.builtin.command: scp {{ report_file }} {{ destination }}
  when: copy_reports == "true"

